# ===============================
# CONFIGURACIÓN GENERAL
# ===============================
spring.application.name=biblioteca-api

# ===============================
# PUERTO DEL SERVIDOR
# ===============================
server.port=8085

# ===============================
# BASE DE DATOS H2
# ===============================
spring.datasource.url=jdbc:h2:mem:biblioteca_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# CONSOLA H2
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# ===============================
# LOGS (OPCIONAL PERO ÚTIL)
# ===============================
logging.level.org.springframework=INFO
logging.level.com.universidad.patrones=DEBUG

# ===============================
# EVITAR ERROR DE TEMPLATES
# ===============================
spring.thymeleaf.check-template-location=false